<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\AISalesAgent.Application\AISalesAgent.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\AISalesAgent.Infrastructure\AISalesAgent.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Infrastructure\AISalesAgent.Persistence\AISalesAgent.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.6" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.6" />
  </ItemGroup>

</Project>
